"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { Beer,CheckCircle2,Clock3,MapPin,PackageCheck,Minus,Send,Truck,XCircle,Power } from "lucide-react";
import { AuthGate } from "@/components/auth-gate";
import { Shell } from "@/components/shell";
import { useApp } from "@/components/app-provider";
import { createClient } from "@/lib/supabase/client";
import styles from "./bachelorando.module.css";

type Person={name:string|null;avatar_url:string|null};
type Order={id:string;requester_id:string;item:string;quantity:number;seat:string;note:string|null;status:"open"|"claimed"|"delivered"|"cancelled";claimed_by:string|null;created_at:string;claimed_at:string|null;delivered_at:string|null;requester:Person|null;courier:Person|null};
const presets=["🍺 Bier","💧 Wasser","🥤 Softdrink","🍿 Snack"];

export default function BachelorandoPage(){
 const {profile,session}=useApp();
 const [orders,setOrders]=useState<Order[]>([]);const[isNewBachelor,setIsNewBachelor]=useState(false);const[enabled,setEnabled]=useState(true);const[serverIsAdmin,setServerIsAdmin]=useState(false);const[selectedPreset,setSelectedPreset]=useState("🍺 Bier");const[customItem,setCustomItem]=useState("");const[quantity,setQuantity]=useState(1);const[seat,setSeat]=useState("");const[note,setNote]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState("");
 const isAdmin=Boolean(profile?.is_admin&&serverIsAdmin);
 const supabase=useMemo(()=>createClient(),[]);
 const api=useCallback(async(body?:Record<string,unknown>)=>{if(!session?.access_token)throw new Error("Nicht angemeldet.");const r=await fetch("/api/bachelorando",{method:body?"POST":"GET",headers:{Authorization:`Bearer ${session.access_token}`,...(body?{"Content-Type":"application/json"}: {})},body:body?JSON.stringify(body):undefined,cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Bachelorando-Fehler");return j},[session?.access_token]);
 const load=useCallback(async()=>{if(!session?.access_token)return;try{const j=await api();setOrders(j.orders??[]);setIsNewBachelor(Boolean(j.isNewBachelor));setEnabled(j.enabled!==false);setServerIsAdmin(Boolean(j.isAdmin))}catch(e){setStatus(e instanceof Error?e.message:"Laden fehlgeschlagen.")}},[api,session?.access_token]);
 useEffect(()=>{void load();if(!session?.access_token)return;const channel=supabase.channel("bachelorando-live").on("postgres_changes",{event:"*",schema:"public",table:"bachelorando_orders"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"app_settings"},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[load,session?.access_token,supabase]);
 async function act(key:string,body:Record<string,unknown>){setBusy(key);setStatus("");try{const j=await api(body);if(j.enabled!==undefined)setEnabled(Boolean(j.enabled));setStatus(j.sent!==undefined?`Bestellung raus! ${j.sent} Neu-Bachelor-Geräte benachrichtigt.`:"Aktualisiert.");await load()}catch(e){setStatus(e instanceof Error?e.message:"Aktion fehlgeschlagen.")}finally{setBusy("")}}
 async function submit(){const finalItem=customItem.trim()||selectedPreset;if(!finalItem){setStatus("Was möchtest du bestellen?");return}if(!seat.trim()){setStatus("Bitte Platznummer oder Standort angeben.");return}await act("create",{action:"create",item:finalItem,quantity,seat:seat.trim(),note:note.trim()});setCustomItem("");setNote("")}
 const active=orders.filter(o=>o.status==="open"||o.status==="claimed");const done=orders.filter(o=>o.status==="delivered").slice(0,8);
 return <AuthGate><Shell>
  <section className={styles.hero}><div className={styles.heroTop}><div className={styles.heroIcon}><Beer/></div><div><span className="eyebrow">BACHELORANDO</span><h1>{enabled?"Durst kennt keine Liefergebühr.":"Bachelorando hat heute keinen Bock."}</h1><p>{enabled?"Bestellen. Neu-Bachelor losschicken. Prost.":"Aktuell sind keine Bestellungen verfügbar. Musst selber gucken, wie du an dein Bier kommst. Viel Erfolg. 🍺😄"}</p></div></div>{isAdmin&&<button type="button" className={enabled?"danger-button":"primary-button"} disabled={busy==="toggle"} onClick={()=>act("toggle",{action:"toggle",enabled:!enabled})}><Power size={17}/>{enabled?"Bachelorando deaktivieren":"Bachelorando aktivieren"}</button>}{enabled&&(isNewBachelor?<div className={styles.newBachelorHint}><Truck size={17}/>Du bist Neu-Bachelor – du kannst offene Bestellungen übernehmen, erledigen oder stornieren.</div>:<div className={styles.customerHint}><Beer size={17}/>Deine Bestellung geht per Push direkt an alle Neu-Bachelor.</div>)}</section>
  {!enabled?<section className={styles.form}><div style={{textAlign:"center",padding:"18px 8px"}}><div style={{fontSize:"3rem",marginBottom:8}}>🚫🍺</div><h2>Heute ist Selbstbedienung.</h2><p>Die Neu-Bachelor haben Sendepause. Wer Durst hat, muss die Beine selbst in die Hand nehmen.</p>{isAdmin&&<p><strong>Admin-Hinweis:</strong> Oben kannst du Bachelorando jederzeit wieder einschalten.</p>}</div></section>:<>
  <section className={styles.form}><div className={styles.presetGrid}>{presets.map(p=><button type="button" key={p} className={selectedPreset===p&&!customItem.trim()?styles.active:""} onClick={()=>{setSelectedPreset(p);setCustomItem("")}}>{p}</button>)}</div><input value={customItem} maxLength={80} onChange={e=>setCustomItem(e.target.value)} placeholder="Freitext optional – sonst gilt die Auswahl oben"/><div className={styles.row}><div className={styles.quantity}><button type="button" onClick={()=>setQuantity(v=>Math.max(1,v-1))}><Minus/></button><input value={quantity} inputMode="numeric" onChange={e=>setQuantity(Math.max(1,Math.min(20,Number(e.target.value)||1)))}/><button type="button" onClick={()=>setQuantity(v=>Math.min(20,v+1))}><span aria-hidden="true">+</span></button></div><input value={seat} maxLength={80} onChange={e=>setSeat(e.target.value)} placeholder="Platznummer / Standort, z. B. Bus Platz 23"/></div><input value={note} maxLength={240} onChange={e=>setNote(e.target.value)} placeholder="Bemerkung optional – z. B. bitte eiskalt 😄"/><button type="button" className={`primary-button ${styles.submit}`} disabled={busy==="create"} onClick={submit}><Send size={18}/>{busy==="create"?"Bestellung wird gesendet …":"Jetzt bestellen"}</button>{status&&<div className={styles.status}>{status}</div>}</section>
  <section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">LIVE</span><h2>Offene Bestellungen</h2><p>{active.length} aktuell unterwegs oder noch frei.</p></div></div><div className={styles.orders}>{active.map(o=>{const canManage=o.requester_id===profile?.id||isNewBachelor;return <article key={o.id} className={styles.card}><div><div className={styles.meta}><strong>{o.requester?.name||"Bachelor"}</strong><span className={styles.time}>{new Date(o.created_at).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Berlin"})}</span></div><div className={styles.item}>{o.quantity}× {o.item}</div><div className={styles.place}><MapPin size={15}/>{o.seat}</div>{o.note&&<div className={styles.note}>{o.note}</div>}{o.status==="open"?<div className={styles.state}><Clock3 size={15}/>Wartet auf einen Neu-Bachelor</div>:<div className={`${styles.state} ${styles.claimed}`}><Truck size={15}/>{o.courier?.name||"Neu-Bachelor"} ist dran</div>}</div><div className={styles.actions}>{isNewBachelor&&o.status==="open"&&<button type="button" className={styles.claim} disabled={busy===o.id} onClick={()=>act(o.id,{action:"claim",orderId:o.id})}><Truck size={16}/> Ich übernehme</button>}{canManage&&<button type="button" className={styles.deliver} disabled={busy===o.id} onClick={()=>act(o.id,{action:"deliver",orderId:o.id})}><PackageCheck size={16}/> Erledigt</button>}{canManage&&<button type="button" className={styles.cancel} disabled={busy===o.id} onClick={()=>act(o.id,{action:"cancel",orderId:o.id})}><XCircle size={16}/> Stornieren</button>}</div></article>})}{!active.length&&<div className={styles.empty}>Gerade alles trocken … äh, erledigt. Keine offenen Bestellungen.</div>}</div></section>
  {done.length>0&&<section className={styles.section}><div className={styles.sectionHead}><div><span className="eyebrow">ERLEDIGT</span><h2>Frisch geliefert</h2></div></div><div className={styles.orders}>{done.map(o=><article key={o.id} className={`${styles.card} ${styles.delivered}`}><div><div className={styles.meta}><strong>{o.requester?.name||"Bachelor"}</strong></div><div className={styles.item}>{o.quantity}× {o.item}</div><div className={`${styles.state} ${styles.delivered}`}><CheckCircle2 size={15}/>Erledigt{o.courier?.name?` von ${o.courier.name}`:""}</div></div></article>)}</div></section>}
  </>}
  {status&&!enabled&&<div className={styles.status}>{status}</div>}
 </Shell></AuthGate>
}
