"use client";
import {useCallback,useEffect,useMemo,useState} from"react";import{RefreshCw,CheckCircle2,XCircle,Smartphone,BellRing,MapPin,Clock3}from"lucide-react";import{AuthGate}from"@/components/auth-gate";import{Shell}from"@/components/shell";import{useApp}from"@/components/app-provider";
type Member={id:string;name:string;avatar_url?:string|null;share_location:boolean;push_registered:boolean;device:any};
export default function AdminDevices(){const{session}=useApp();const[members,setMembers]=useState<Member[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{if(!session)return;setLoading(true);const r=await fetch("/api/admin/device-status",{headers:{Authorization:`Bearer ${session.access_token}`}});const j=await r.json();if(!r.ok)setError(j.error||"Fehler");else{setMembers(j.members||[]);setError("")}setLoading(false)},[session]);useEffect(()=>{load()},[load]);
 const complete=useMemo(()=>members.filter(m=>m.device?.installed&&m.push_registered&&m.share_location).length,[members]);
 return <AuthGate admin><Shell><div className="page-heading"><span className="eyebrow">GERÄTEÜBERSICHT</span><h1>Teilnehmer bereit?</h1><p>Installation, Push, Standort und letzte Aktivität auf einen Blick.</p></div><section className="device-admin-summary"><strong>{complete} / {members.length} vollständig eingerichtet</strong><div><i style={{width:`${members.length?complete/members.length*100:0}%`}}/></div></section>{error&&<div className="error">{error}</div>}<button className="secondary-button device-admin-refresh" onClick={load} disabled={loading}><RefreshCw/>{loading?"Aktualisiert …":"Aktualisieren"}</button><div className="device-admin-list">{members.map(m=>{const d=m.device;return <article className="device-admin-row" key={m.id}><div className="device-admin-person">{m.avatar_url?<img src={m.avatar_url} alt=""/>:<span>{m.name.slice(0,2).toUpperCase()}</span>}<div><strong>{m.name}</strong><small>{d?`${d.platform||"?"} · ${d.browser||"?"}`:"Noch kein Gerätebericht"}</small></div></div><Status icon={Smartphone} ok={Boolean(d?.installed)} label="App"/><Status icon={BellRing} ok={m.push_registered} label="Push"/><Status icon={MapPin} ok={m.share_location} label="Standort"/><InfoStatus icon={Clock3} label="Zuletzt online" value={d?.last_seen_at?relative(d.last_seen_at):"noch nie"}/></article>})}</div></Shell></AuthGate>}
function Status({icon:Icon,ok,label}:{icon:any;ok:boolean;label:string}){return <div className={`device-admin-status ${ok?"ok":"bad"}`}><Icon/><span>{label}</span>{ok?<CheckCircle2/>:<XCircle/>}</div>}
function InfoStatus({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="device-admin-status info"><Icon/><span><b>{label}</b><small>{value}</small></span></div>}
function relative(v:string){const diff=Math.max(0,Date.now()-new Date(v).getTime());const m=Math.floor(diff/60000);if(m<1)return"gerade eben";if(m<60)return`vor ${m} Min.`;const h=Math.floor(m/60);if(h<24)return`vor ${h} Std.`;const d=Math.floor(h/24);return`vor ${d} Tag${d===1?"":"en"}`}
