"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Hotel, MapPin, PauseCircle, Route, Shirt, Siren, Smartphone, ChevronRight } from "lucide-react";
import { AuthGate } from "@/components/auth-gate";import { Shell } from "@/components/shell";import { PushProfileSetting } from "@/components/push-settings";import { ImageCropper } from "@/components/image-cropper";import { useApp } from "@/components/app-provider";import { createClient } from "@/lib/supabase/client";
const sizes=["XS","S","M","L","XL","XXL","3XL","4XL"];
const statusOptions=[{value:"bereit",label:"Bereit",icon:CheckCircle2},{value:"unterwegs",label:"Unterwegs",icon:Route},{value:"im Hotel",label:"Im Hotel",icon:Hotel},{value:"komme später",label:"Komme später",icon:Clock3},{value:"brauche Pause",label:"Brauche Pause",icon:PauseCircle},{value:"brauche Hilfe",label:"Brauche Hilfe",icon:Siren}];
export default function ProfilePage(){
 const {profile,session,refreshProfile}=useApp();const fallback=useMemo(()=>splitName(profile?.name||""),[profile?.name]);const [preview,setPreview]=useState(profile?.avatar_url||"");const [avatarFile,setAvatarFile]=useState<File|null>(null);const [cropFile,setCropFile]=useState<File|null>(null);const [size,setSize]=useState("");const [street,setStreet]=useState("");const [postal,setPostal]=useState("");const [city,setCity]=useState("");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const [helpBusy,setHelpBusy]=useState(false);const supabase=useMemo(()=>createClient(),[]);
 useEffect(()=>{if(!profile?.id)return;supabase.from("member_private_details").select("clothing_size,street,postal_code,city,home_address").eq("user_id",profile.id).maybeSingle().then(({data})=>{setSize(data?.clothing_size||"");setStreet(data?.street||data?.home_address?.split("\n")[0]||"");setPostal(data?.postal_code||"");setCity(data?.city||"")})},[profile?.id,supabase]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!profile)return;setBusy(true);setStatus("");const f=new FormData(e.currentTarget);const first_name=String(f.get("first_name")).trim(),last_name=String(f.get("last_name")).trim(),name=`${first_name} ${last_name}`.trim();let avatar_url=profile.avatar_url;if(avatarFile){const safe=avatarFile.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${profile.id}/${Date.now()}-${safe}`;const up=await supabase.storage.from("avatars").upload(path,avatarFile,{upsert:true});if(up.error){setStatus(up.error.message);setBusy(false);return}avatar_url=supabase.storage.from("avatars").getPublicUrl(path).data.publicUrl}const home_address=`${street}\n${postal} ${city}`.trim();const [{error},{error:privateError}]=await Promise.all([supabase.from("profiles").update({first_name,last_name,name,phone:String(f.get("phone")).trim(),avatar_url}).eq("id",profile.id),supabase.from("member_private_details").upsert({user_id:profile.id,clothing_size:size||null,street:street||null,postal_code:postal||null,city:city||null,home_address,updated_at:new Date().toISOString()},{onConflict:"user_id"})]);const err=error||privateError;if(err)setStatus(err.message);else{setStatus("Profil gespeichert.");setAvatarFile(null);await refreshProfile()}setBusy(false)}
 async function setParticipantStatus(next:string){if(!profile)return;const {error}=await supabase.from("profiles").update({participant_status:next,status_updated_at:new Date().toISOString()}).eq("id",profile.id);setStatus(error?error.message:`Status auf „${next}“ gesetzt.`);if(!error)await refreshProfile()}
 async function sendHelp(){if(!session||helpBusy)return;if(!confirm("Wirklich einen Hilferuf an alle Teilnehmer senden? Dein aktueller Standort wird geteilt."))return;setHelpBusy(true);setStatus("Standort wird ermittelt …");navigator.geolocation.getCurrentPosition(async p=>{const r=await fetch("/api/help-alert",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy})});const j=await r.json();setStatus(r.ok?`Hilferuf gesendet. ${j.sent??0} Geräte wurden benachrichtigt.`:j.error||"Hilferuf fehlgeschlagen.");setHelpBusy(false);if(r.ok)await refreshProfile()},()=>{setStatus("Standort konnte nicht ermittelt werden.");setHelpBusy(false)},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
 const first=(profile as any)?.first_name||fallback.first,last=(profile as any)?.last_name||fallback.last;
 return <AuthGate><Shell><div className="page-heading"><span className="eyebrow">DEIN PROFIL</span><h1>Meine Daten & Status</h1><p>Profil, Tourstatus, Push-Einstellungen und Hilfe an einem Ort.</p></div><form className="profile-card" onSubmit={save}><label className="profile-avatar-upload">{preview?<img src={preview} alt=""/>:<span>Foto</span>}<input type="file" accept="image/*" onChange={(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(file)setCropFile(file);e.target.value=""}}/></label><small>Tippe auf das Foto, um ein neues Bild auszuwählen und zuzuschneiden.</small><div className="two-cols"><input name="first_name" defaultValue={first} placeholder="Vorname" required/><input name="last_name" defaultValue={last} placeholder="Nachname" required/></div><input name="phone" defaultValue={profile?.phone||""} placeholder="Handynummer" required/>
 <div className="private-profile-section"><div className="private-profile-heading"><Shirt/><div><span className="eyebrow">PRIVATE ZUSATZDATEN</span><h3>Kleidung & Anschrift</h3></div></div><p>Diese Angaben können ausschließlich du selbst und die Admins sehen.</p><div className="size-picker"><span>Kleidergröße</span><div>{sizes.map(s=><button type="button" key={s} className={size===s?"active":""} onClick={()=>setSize(s)}>{s}</button>)}</div></div><input value={street} onChange={e=>setStreet(e.target.value)} placeholder="Straße und Hausnummer"/><div className="address-row"><input value={postal} onChange={e=>setPostal(e.target.value)} inputMode="numeric" maxLength={5} placeholder="PLZ"/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ort"/></div></div><button className="primary-button" disabled={busy}>{busy?"Speichert …":"Profil speichern"}</button></form>
 <section className="profile-status-card"><div className="profile-section-head"><MapPin/><div><span className="eyebrow">MEIN TOURSTATUS</span><h2>Wie ist dein Stand?</h2></div></div><div className="profile-status-grid">{statusOptions.map(({value,label,icon:Icon})=><button type="button" key={value} className={`profile-status-option status-${slug(value)} ${profile?.participant_status===value?"active":""}`} onClick={()=>setParticipantStatus(value)}><Icon/><span>{label}</span></button>)}</div></section><section className="profile-help-card"><div><span className="eyebrow">NUR IM NOTFALL</span><h2>Hilfe benötigt?</h2><p>Alle Teilnehmer erhalten sofort eine Push-Nachricht. Dein Standort wird neu abgerufen und geteilt.</p></div><button type="button" className="help-alert-button" disabled={helpBusy} onClick={sendHelp}><AlertTriangle/>{helpBusy?"Hilferuf wird gesendet …":"Hilfe an alle senden"}</button></section>{status&&<div className="status">{status}</div>}<PushProfileSetting/><Link href="/device-check" className="profile-setting-card device-check-profile-link"><div className="profile-setting-icon active"><Smartphone/></div><div className="profile-setting-copy"><h3>Gerät prüfen</h3><p>Installation, Internet, Standort und Push dieses Handys kontrollieren.</p></div><ChevronRight/></Link>{cropFile&&<ImageCropper file={cropFile} aspect={1} round title="Profilfoto zuschneiden" onCancel={()=>setCropFile(null)} onComplete={(file,url)=>{setAvatarFile(file);setPreview(url);setCropFile(null)}}/>}</Shell></AuthGate>}
function splitName(name:string){const p=name.trim().split(/\s+/).filter(Boolean);return{first:p.shift()||"",last:p.join(" ")}}function slug(v:string){return v.toLowerCase().replace(/\s+/g,"-").replace(/ä/g,"ae")}
