"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ListMusic, Music2, Play, Plus, RefreshCw, Search, SkipForward, ThumbsUp } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { useApp } from "./app-provider";

type SearchTrack={id:string;uri:string;title:string;artist:string;album:string;image:string|null;durationMs:number;externalUrl:string|null};
type QueueTrack={id:string;spotify_id:string;spotify_uri:string;title:string;artist:string;album:string|null;image_url:string|null;duration_ms:number|null;requested_by:string;requested_at:string;status:string;sent_at:string|null};
type Vote={track_id:string;user_id:string};
type Device={id:string;name:string;type:string;isActive:boolean;volume:number|null};
type Current={id:string;uri:string;title:string;artist:string;image:string|null;progressMs:number;durationMs:number;isPlaying:boolean;device:{id:string;name:string}|null};

export function AdminJukeboxCard(){
  const {profile}=useApp();
  const supabase=useMemo(()=>createClient(),[]);
  const [query,setQuery]=useState("");const [results,setResults]=useState<SearchTrack[]>([]);const [tracks,setTracks]=useState<QueueTrack[]>([]);const [votes,setVotes]=useState<Vote[]>([]);const [devices,setDevices]=useState<Device[]>([]);const [selectedDevice,setSelectedDevice]=useState("");const [current,setCurrent]=useState<Current|null>(null);const [connected,setConnected]=useState(false);const [account,setAccount]=useState<string>("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");

  const authHeader=useCallback(async()=>{const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error("Nicht angemeldet.");return {Authorization:`Bearer ${token}`}},[supabase]);
  const loadQueue=useCallback(async()=>{if(!profile?.is_admin)return;const [t,v,s]=await Promise.all([supabase.from("jukebox_tracks").select("*").in("status",["queued","sent"]).order("requested_at"),supabase.from("jukebox_votes").select("track_id,user_id"),supabase.from("jukebox_settings").select("selected_device_id").eq("id",1).maybeSingle()]);setTracks((t.data as QueueTrack[])??[]);setVotes((v.data as Vote[])??[]);if(s.data?.selected_device_id)setSelectedDevice(s.data.selected_device_id)},[profile?.is_admin,supabase]);
  const loadPlayer=useCallback(async()=>{if(!profile?.is_admin)return;try{const headers=await authHeader();const res=await fetch("/api/spotify/player",{headers,cache:"no-store"});const data=await res.json();setConnected(Boolean(data.connected));setDevices(data.devices??[]);setCurrent(data.current??null);setAccount(data.account?.spotify_display_name||data.account?.spotify_user_id||"");if(!selectedDevice){const active=(data.devices??[]).find((d:Device)=>d.isActive);if(active?.id)setSelectedDevice(active.id)}}catch{}},[authHeader,profile?.is_admin,selectedDevice]);
  useEffect(()=>{if(!profile?.is_admin)return;void loadQueue();void loadPlayer();const channel=supabase.channel("jukebox-admin-live").on("postgres_changes",{event:"*",schema:"public",table:"jukebox_tracks"},()=>loadQueue()).on("postgres_changes",{event:"*",schema:"public",table:"jukebox_votes"},()=>loadQueue()).subscribe();const timer=window.setInterval(()=>void loadPlayer(),10000);return()=>{window.clearInterval(timer);supabase.removeChannel(channel)}},[profile?.is_admin,loadQueue,loadPlayer,supabase]);
  if(!profile?.is_admin)return null;

  async function connect(){setBusy(true);setMessage("");try{const headers=await authHeader();const res=await fetch("/api/spotify/connect",{method:"POST",headers});const data=await res.json();if(!res.ok)throw new Error(data.error||"Spotify-Verbindung fehlgeschlagen.");window.location.assign(data.url)}catch(e){setMessage(e instanceof Error?e.message:"Fehler");setBusy(false)}}
  async function search(e:FormEvent){e.preventDefault();if(query.trim().length<2)return;setBusy(true);setMessage("");try{const headers=await authHeader();const res=await fetch(`/api/spotify/search?q=${encodeURIComponent(query.trim())}`,{headers});const data=await res.json();if(!res.ok)throw new Error(data.error||"Suche fehlgeschlagen.");setResults(data.tracks??[])}catch(e){setMessage(e instanceof Error?e.message:"Fehler")}finally{setBusy(false)}}
  async function addTrack(track:SearchTrack){if(!profile)return;const {data,error}=await supabase.from("jukebox_tracks").insert({spotify_id:track.id,spotify_uri:track.uri,title:track.title,artist:track.artist,album:track.album,image_url:track.image,duration_ms:track.durationMs,requested_by:profile.id}).select("id").single();if(error){setMessage(error.message);return}await supabase.from("jukebox_votes").insert({track_id:data.id,user_id:profile.id});setMessage(`${track.title} ist in der Jukebox.`);setResults([]);setQuery("");await loadQueue()}
  async function toggleVote(trackId:string){if(!profile)return;const has=votes.some(v=>v.track_id===trackId&&v.user_id===profile.id);if(has)await supabase.from("jukebox_votes").delete().eq("track_id",trackId).eq("user_id",profile.id);else await supabase.from("jukebox_votes").insert({track_id:trackId,user_id:profile.id});await loadQueue()}
  const ranked=[...tracks].sort((a,b)=>{const av=votes.filter(v=>v.track_id===a.id).length,bv=votes.filter(v=>v.track_id===b.id).length;return bv-av||new Date(a.requested_at).getTime()-new Date(b.requested_at).getTime()});
  async function chooseDevice(id:string){setSelectedDevice(id);await supabase.from("jukebox_settings").update({selected_device_id:id,updated_at:new Date().toISOString()}).eq("id",1);if(!id)return;try{const headers={...(await authHeader()),"Content-Type":"application/json"};const res=await fetch("/api/spotify/player",{method:"POST",headers,body:JSON.stringify({action:"transfer",deviceId:id})});if(!res.ok)throw new Error("Gerät konnte nicht übernommen werden.");await loadPlayer();setMessage("Wiedergabegerät gespeichert.")}catch(e){setMessage(e instanceof Error?e.message:"Gerätewechsel fehlgeschlagen.")}}
  async function playWinner(){const winner=ranked.find(t=>t.status==="queued");if(!winner){setMessage("Keine offenen Songs in der Warteschlange.");return}if(!selectedDevice){setMessage("Bitte zuerst das zentrale Wiedergabegerät auswählen.");return}setBusy(true);setMessage("");try{const headers={...(await authHeader()),"Content-Type":"application/json"};const res=await fetch("/api/spotify/player",{method:"POST",headers,body:JSON.stringify({action:"play",uri:winner.spotify_uri,deviceId:selectedDevice})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"Konnte Song nicht auf dem ausgewählten Spotify-Gerät starten.");await supabase.from("jukebox_tracks").update({status:"sent",sent_at:new Date().toISOString()}).eq("id",winner.id);setMessage(`${winner.title} läuft jetzt auf dem ausgewählten Gerät.`);await Promise.all([loadQueue(),loadPlayer()])}catch(e){setMessage(e instanceof Error?e.message:"Fehler")}finally{setBusy(false)}}
  async function skip(){setBusy(true);try{const headers={...(await authHeader()),"Content-Type":"application/json"};const res=await fetch("/api/spotify/player",{method:"POST",headers,body:JSON.stringify({action:"skip",deviceId:selectedDevice||undefined})});if(!res.ok)throw new Error("Skip fehlgeschlagen.");await loadPlayer()}catch(e){setMessage(e instanceof Error?e.message:"Fehler")}finally{setBusy(false)}}

  return <section id="jukebox" style={{marginTop:14,border:"1px solid #285b3d",borderRadius:24,background:"linear-gradient(145deg,#142219,#0c0f0d)",overflow:"hidden",boxShadow:"0 18px 55px rgba(0,0,0,.28)"}}>
    <div style={{padding:18,display:"flex",gap:12,alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid rgba(255,255,255,.08)"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{width:48,height:48,borderRadius:16,display:"grid",placeItems:"center",background:"#1DB954",color:"#07150b"}}><ListMusic/></div><div><span className="eyebrow" style={{color:"#4fe27f"}}>ADMIN TEST · SPOTIFY</span><h2 style={{margin:"3px 0 0",fontSize:"1.3rem"}}>Bachelor Jukebox</h2></div></div><button onClick={()=>{void loadQueue();void loadPlayer()}} className="icon-button" aria-label="Jukebox aktualisieren"><RefreshCw size={18}/></button></div>
    <div style={{padding:18,display:"grid",gap:14}}>
      {!connected?<div style={{display:"grid",gap:10}}><p style={{margin:0,color:"#aaa"}}>Einmalige Spotify-Autorisierung erforderlich. Danach läuft die Jukebox ohne erneute Anmeldung.</p><button className="primary-button" disabled={busy} onClick={connect}><Music2 size={18}/> Spotify einmalig autorisieren</button></div>:<>
        <div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,alignItems:"center"}}><label><span style={{fontSize:12,color:"#999",display:"block",marginBottom:6}}>ZENTRALES WIEDERGABEGERÄT {account&&`· ${account}`} · NUR ADMIN</span><select value={selectedDevice} onChange={e=>void chooseDevice(e.target.value)} style={{width:"100%",border:"1px solid #303030",background:"#181818",color:"#fff",borderRadius:14,padding:13}}><option value="">Spotify-Gerät auswählen …</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name} · {d.type}{d.isActive?" · aktiv":""}</option>)}</select></label><button className="icon-button" disabled={busy||!current} onClick={skip} title="Aktuellen Song überspringen"><SkipForward/></button></div>
        {current&&<div style={{display:"grid",gridTemplateColumns:"58px 1fr auto",gap:12,alignItems:"center",padding:12,borderRadius:18,background:"rgba(29,185,84,.1)",border:"1px solid rgba(29,185,84,.25)"}}>{current.image?<img src={current.image} alt="" style={{width:58,height:58,objectFit:"cover",borderRadius:12}}/>:<div style={{width:58,height:58,borderRadius:12,display:"grid",placeItems:"center",background:"#222"}}><Music2/></div>}<div style={{minWidth:0}}><span style={{fontSize:11,color:"#4fe27f",fontWeight:800}}>JETZT LÄUFT</span><strong style={{display:"block",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{current.title}</strong><small style={{color:"#aaa"}}>{current.artist}</small></div>{current.isPlaying&&<Play size={20} fill="currentColor"/>}</div>}
        <form onSubmit={search} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Song oder Interpret suchen …"/><button className="primary-button" disabled={busy||query.trim().length<2} aria-label="Spotify durchsuchen"><Search size={18}/></button></form>
        {results.length>0&&<div style={{display:"grid",gap:7}}>{results.map(t=><div key={t.id} style={{display:"grid",gridTemplateColumns:"48px 1fr auto",gap:10,alignItems:"center",padding:9,borderRadius:14,background:"#151515"}}>{t.image?<img src={t.image} alt="" style={{width:48,height:48,objectFit:"cover",borderRadius:9}}/>:<div/>}<div style={{minWidth:0}}><strong style={{display:"block",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{t.title}</strong><small style={{color:"#999"}}>{t.artist}</small></div><button className="icon-button" onClick={()=>void addTrack(t)} title="Zur Jukebox hinzufügen"><Plus/></button></div>)}</div>}
        <div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:8}}><strong>Warteschlange & Voting</strong><button className="primary-button" disabled={busy||!selectedDevice||!ranked.some(t=>t.status==="queued")} onClick={()=>void playWinner()} style={{padding:"10px 12px"}}>Top-Song jetzt abspielen</button></div>{ranked.length===0?<div className="empty-card">Noch keine Songwünsche.</div>:<div style={{display:"grid",gap:7}}>{ranked.map((t,index)=>{const count=votes.filter(v=>v.track_id===t.id).length;const mine=votes.some(v=>v.track_id===t.id&&v.user_id===profile.id);return <div key={t.id} style={{display:"grid",gridTemplateColumns:"32px 44px 1fr auto",gap:9,alignItems:"center",padding:9,borderRadius:14,background:t.status==="sent"?"rgba(29,185,84,.1)":"#151515",border:t.status==="sent"?"1px solid rgba(29,185,84,.22)":"1px solid transparent"}}><strong style={{textAlign:"center",color:index===0?"#4fe27f":"#777"}}>{index+1}</strong>{t.image_url?<img src={t.image_url} alt="" style={{width:44,height:44,objectFit:"cover",borderRadius:9}}/>:<div/>}<div style={{minWidth:0}}><strong style={{display:"block",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{t.title}</strong><small style={{color:"#999"}}>{t.artist}{t.status==="sent"?" · abgespielt/gesendet":""}</small></div><button onClick={()=>void toggleVote(t.id)} style={{border:0,borderRadius:999,padding:"9px 11px",display:"flex",gap:6,alignItems:"center",background:mine?"#1DB954":"#252525",color:mine?"#07150b":"#fff",fontWeight:900}}><ThumbsUp size={15}/>{count}</button></div>})}</div>}</div>
      </>}
      {message&&<div className="status" style={{margin:0}}>{message}</div>}
    </div>
  </section>;
}
