"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Film, Pause, Play, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type TourMedia={id:string;title:string;category:string;description:string|null;storage_path:string;duration_seconds:number|null;sort_order:number;media_type:"audio"|"video";mime_type:string|null};

export function SoundboardModal({open,onClose}:{open:boolean;onClose:()=>void}){
  const [items,setItems]=useState<TourMedia[]>([]);const [loading,setLoading]=useState(false);const [active,setActive]=useState<TourMedia|null>(null);const [signedUrl,setSignedUrl]=useState("");const [isPlaying,setIsPlaying]=useState(false);const [progress,setProgress]=useState(0);const [duration,setDuration]=useState(0);const [error,setError]=useState("");
  const audioRef=useRef<HTMLAudioElement|null>(null);const videoRef=useRef<HTMLVideoElement|null>(null);const onCloseRef=useRef(onClose);const supabase=useMemo(()=>createClient(),[]);
  useEffect(()=>{onCloseRef.current=onClose},[onClose]);
  const stop=useCallback(()=>{const audio=audioRef.current;if(audio){audio.pause();audio.removeAttribute("src");audio.load();audioRef.current=null}if(videoRef.current)videoRef.current.pause();setActive(null);setSignedUrl("");setIsPlaying(false);setProgress(0);setDuration(0)},[]);
  const load=useCallback(async()=>{const {data,error}=await supabase.from("tour_sounds").select("id,title,category,description,storage_path,duration_seconds,sort_order,media_type,mime_type").eq("is_visible",true).order("category").order("sort_order").order("created_at");if(error)setError(error.message);else setItems((data as TourMedia[])??[])},[supabase]);
  useEffect(()=>{if(!open)return;let mounted=true;setLoading(true);setError("");load().finally(()=>mounted&&setLoading(false));document.body.classList.add("soundboard-open");const key=(event:KeyboardEvent)=>{if(event.key==="Escape")onCloseRef.current()};document.addEventListener("keydown",key);const channel=supabase.channel("public-media-live").on("postgres_changes",{event:"*",schema:"public",table:"tour_sounds"},load).subscribe();return()=>{mounted=false;document.removeEventListener("keydown",key);document.body.classList.remove("soundboard-open");supabase.removeChannel(channel);stop()}},[open,load,stop,supabase]);
  async function openMedia(item:TourMedia){if(active?.id===item.id&&item.media_type==="audio"&&audioRef.current){if(audioRef.current.paused){await audioRef.current.play();setIsPlaying(true)}else{audioRef.current.pause();setIsPlaying(false)}return}stop();setError("");const {data,error}=await supabase.storage.from("tour-sounds").createSignedUrl(item.storage_path,3600);if(error||!data?.signedUrl){setError("Medium konnte nicht geladen werden.");return}setActive(item);setSignedUrl(data.signedUrl);setDuration(item.duration_seconds||0);if(item.media_type==="video")return;const audio=new Audio(data.signedUrl);audio.preload="auto";audioRef.current=audio;audio.ontimeupdate=()=>{if(audioRef.current===audio){setProgress(audio.currentTime);setDuration(audio.duration||item.duration_seconds||0)}};audio.onplay=()=>setIsPlaying(true);audio.onpause=()=>setIsPlaying(false);audio.onended=stop;audio.onerror=()=>{setError("Audio konnte nicht abgespielt werden.");stop()};try{await audio.play()}catch{setError("Audio konnte nicht gestartet werden.");stop()}}
  if(!open||typeof document==="undefined")return null;
  const categories=Array.from(new Set(items.map(item=>item.category)));
  return createPortal(<div className="soundboard-backdrop" onPointerDown={event=>{if(event.target===event.currentTarget)onCloseRef.current()}}><section className="soundboard-modal media-modal" role="dialog" aria-modal="true" aria-label="Tour-Medien"><header className="soundboard-header"><div><span className="eyebrow">DIE BESTEN MOMENTE</span><h2><Film/> Tour-Medien</h2><p>Sounds und Videos aus dieser und früheren Touren.</p></div><button type="button" className="soundboard-close" onClick={()=>onCloseRef.current()} aria-label="Schließen"><X/></button></header>{error&&<div className="error">{error}</div>}<div className="soundboard-scroll">{active?.media_type==="video"&&signedUrl&&<div className="media-video-stage" style={{display:"grid",gap:12,padding:12,marginBottom:16,borderRadius:18,background:"#080808",border:"1px solid rgba(255,255,255,.12)"}}><video ref={videoRef} src={signedUrl} controls playsInline preload="metadata" autoPlay onPlay={()=>setIsPlaying(true)} onPause={()=>setIsPlaying(false)} onEnded={()=>setIsPlaying(false)} style={{display:"block",width:"100%",maxHeight:"58vh",aspectRatio:"16 / 9",objectFit:"contain",background:"#000",borderRadius:12}}/><div style={{display:"grid",gap:8}}><strong>{active.title}</strong>{active.description&&<small>{active.description}</small>}<button type="button" className="secondary-button" onClick={stop}>Video schließen</button></div></div>}{loading?<div className="empty-card">Medien werden geladen …</div>:!items.length?<div className="empty-card">Noch keine Medien freigeschaltet.</div>:categories.map(category=><section className="sound-category" key={category}><h3>{category}</h3><div className="sound-list">{items.filter(item=>item.category===category).map(item=>{const selected=active?.id===item.id;const playing=selected&&isPlaying;const total=selected?duration:(item.duration_seconds||0);return <article className={`sound-row media-row ${selected?"active":""}`} key={item.id}><button type="button" className="sound-play" onClick={()=>openMedia(item)} aria-label={`${item.title} öffnen`}>{item.media_type==="video"?<Film/>:playing?<Pause/>:<Play/>}</button><div className="sound-copy"><span className="media-kind" style={{fontSize:10,fontWeight:800,letterSpacing:1,opacity:.7}}>{item.media_type==="video"?"VIDEO":"AUDIO"}</span><strong>{item.title}</strong>{item.description&&<small>{item.description}</small>}{item.media_type==="audio"&&<div className="sound-progress"><span style={{width:selected&&total?`${Math.min(100,progress/total*100)}%`:"0%"}}/></div>}</div><time>{formatTime(selected?progress:total)}</time></article>})}</div></section>)}</div></section></div>,document.body)
}
function formatTime(seconds:number){if(!Number.isFinite(seconds)||seconds<=0)return "–:––";return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,"0")}`}
